# Generated by Django 2.0 on 2018-11-14 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('force_checkout', 'Can force checkout to restricted borrowers'), ('manage_restrictions', 'Can manage account restrictions'), ('manage_circ_rules', 'Can manage circulation rules'), ('manage_system_preferences', 'Can manage system preferences'), ('modify_holds_priority', 'Can modify hold priority'), ('circulate_place_holds', 'Can circulate & place holds'), ('edit_catalogue', 'Can edit catalog'), ('edit_items', 'Can edit items data'), ('collect_fines_fees', 'Can collect fines & fees'), ('writeoff', 'Can write off fines & fees'), ('delete_anonymize_patrons', 'Can delete old borrowers'), ('edit_calendar', 'Can set calendar'), ('edit_quotations', 'Can edit quotes'), ('edit_news', 'Can write news'), ('edit_patrons', 'Can edit patrons data'), ('export_catalog', 'Can bulk export catalog & items data'), ('import_catalog', 'Can bulk import catalog & items data'), ('import_patrons', 'Can bulk import patrons data'), ('biblio_batchmode', 'Can perorm batch catalog modifications'), ('items_batchmode', 'Can perform batch item modifications'), ('patron_batchmode', 'Can perform batch patron modifications'), ('moderate_comments', 'Can moderate user comments'), ('moderate_tags', 'Can moderate user tags'), ('moderate_suggestions', 'Can moderate user suggestions'), ('upload_local_cover_images', 'Can upload local cover images'), ('upload_patron_images', 'Can upload patron photographs'), ('bulk_import_cover_images', 'Can bulk import local cover images'), ('bulk_import_patron_images', 'Can bulk import patron photographs'), ('execute_reports', 'Can run reports'), ('run_confidential_reports', 'Can run confidential reports'), ('can_borrow', 'Can borrow'), ('can_backup_restore', 'Can perform system backup & restore')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, help_text='Roll number/aadhar numberi/employee number', max_length=16, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Sri', 'Sri'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=4)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.CharField(max_length=50)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
